# Generated by Django 4.1.7 on 2023-03-30 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('organization', models.TextField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('education', models.TextField()),
                ('state', models.TextField()),
                ('women', models.BooleanField()),
                ('lgbt', models.BooleanField()),
                ('ethnicity', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('veteran', models.BooleanField()),
                ('immigrant', models.BooleanField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('users', models.ManyToManyField(to='api.user')),
            ],
        ),
    ]
