# Generated by Django 4.1.7 on 2023-04-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='users',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
