# Generated by Django 4.1.7 on 2023-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_grant_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='grants',
            field=models.ManyToManyField(blank=True, to='api.grant'),
        ),
    ]
