# Generated by Django 4.1.7 on 2023-04-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_grant_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='http://www.image-url.com'),
            preserve_default=False,
        ),
    ]
